# site settings

title: sumantmanne.com
description: sumantmanne.com
url: https://sumantmanne.com
baseurl: ""
permalink: pretty
repo: https://github.com/dpyro/dpyro.github.io
archive: false

# author settings

author:
  name: Sumant Manne
  email: me@sumantmanne.com
photo: /assets/jpg/photo.jpg

# social media links

social:
  github: dpyro
  instagram: mocha.latte.cappuccino
  linkedin: sumantmanne
  email: me@sumantmanne.com
  cv: false

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
